<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductSubCategory;
use App\Models\ProductCategory;
use App\Models\ProductBrand;
use App\Models\UoM;
use App\Models\ProductVat;
use Illuminate\Database\Seeder;

class DemoFoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Adds demo food items like instant noodles, ramen, snacks, and drinks
     */
    public function run(): void
    {
        // First, ensure we have required reference data
        
        // Create Product Category if not exists
        $category = ProductCategory::firstOrCreate(
            ['name' => 'Food & Beverages'],
            ['name' => 'Food & Beverages']
        );

        // Create Product Sub-Category if not exists
        $subCategory = ProductSubCategory::firstOrCreate(
            ['name' => 'Grocery Items'],
            [
                'name' => 'Grocery Items',
                'productCategoryId' => $category->id
            ]
        );

        // Create Product Brand if not exists
        $brand = ProductBrand::firstOrCreate(
            ['name' => 'Various Brands'],
            ['name' => 'Various Brands']
        );

        // Create UoM (Unit of Measure) if not exists
        $uom = UoM::firstOrCreate(
            ['name' => 'Piece'],
            ['name' => 'Piece']
        );

        // Create VAT if not exists
        $vat = ProductVat::firstOrCreate(
            ['title' => 'Standard VAT'],
            [
                'title' => 'Standard VAT',
                'percentage' => 12
            ]
        );

        $products = [
            // Instant Noodles
            [
                'name' => 'Lucky Me Pancit Canton Original',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 10,
                'productSalePrice' => 15,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'LM-PCT-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 20,
                'description' => 'Lucky Me Pancit Canton Original Flavor 60g',
            ],
            [
                'name' => 'Lucky Me Pancit Canton Chilimansi',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 10,
                'productSalePrice' => 15,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'LM-PCT-002',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 20,
                'description' => 'Lucky Me Pancit Canton Chilimansi Flavor 60g',
            ],
            [
                'name' => 'Lucky Me Instant Mami Chicken',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 8,
                'productSalePrice' => 12,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'LM-MAM-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 20,
                'description' => 'Lucky Me Instant Mami Chicken Flavor 55g',
            ],
            [
                'name' => 'Lucky Me Instant Mami Beef',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 8,
                'productSalePrice' => 12,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'LM-MAM-002',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 20,
                'description' => 'Lucky Me Instant Mami Beef Flavor 55g',
            ],
            [
                'name' => 'Nissin Cup Noodles Seafood',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 30,
                'productSalePrice' => 45,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NIS-CUP-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 10,
                'description' => 'Nissin Cup Noodles Seafood Flavor 60g',
            ],
            [
                'name' => 'Nissin Cup Noodles Chicken',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 30,
                'productSalePrice' => 45,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NIS-CUP-002',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 10,
                'description' => 'Nissin Cup Noodles Chicken Flavor 60g',
            ],
            [
                'name' => 'Nissin Yakisoba Hot & Spicy',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 25,
                'productSalePrice' => 38,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NIS-YAK-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 10,
                'description' => 'Nissin Yakisoba Hot & Spicy Flavor',
            ],
            [
                'name' => 'Payless Pancit Canton Extra Big',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 12,
                'productSalePrice' => 18,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'PAY-PCT-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 80,
                'reorderQuantity' => 15,
                'description' => 'Payless Pancit Canton Extra Big 80g',
            ],
            
            // Japanese Ramen
            [
                'name' => 'Nongshim Shin Ramyun',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 50,
                'productSalePrice' => 75,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NON-SHI-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 40,
                'reorderQuantity' => 10,
                'description' => 'Nongshim Shin Ramyun Spicy Korean Noodle 120g',
            ],
            [
                'name' => 'Samyang Hot Chicken Ramen',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 55,
                'productSalePrice' => 85,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'SAM-HOT-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 40,
                'reorderQuantity' => 10,
                'description' => 'Samyang Hot Chicken Flavor Ramen 140g',
            ],
            [
                'name' => 'Samyang 2x Spicy Ramen',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 60,
                'productSalePrice' => 95,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'SAM-2X-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 30,
                'reorderQuantity' => 10,
                'description' => 'Samyang 2x Spicy Hot Chicken Ramen 140g',
            ],
            [
                'name' => 'Ottogi Jin Ramen Mild',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 45,
                'productSalePrice' => 68,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'OTT-JIN-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 35,
                'reorderQuantity' => 10,
                'description' => 'Ottogi Jin Ramen Mild Flavor 120g',
            ],
            [
                'name' => 'Maruchan Ramen Chicken',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 20,
                'productSalePrice' => 35,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'MAR-RAM-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 60,
                'reorderQuantity' => 15,
                'description' => 'Maruchan Ramen Noodle Soup Chicken Flavor 85g',
            ],

            // Drinks
            [
                'name' => 'Coca-Cola Regular 330ml',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 20,
                'productSalePrice' => 30,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'COC-REG-330',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 24,
                'description' => 'Coca-Cola Original Taste 330ml Can',
            ],
            [
                'name' => 'Sprite 330ml',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 20,
                'productSalePrice' => 30,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'SPR-REG-330',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 24,
                'description' => 'Sprite Lemon-Lime 330ml Can',
            ],
            [
                'name' => 'Royal Tru-Orange 330ml',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 18,
                'productSalePrice' => 28,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'ROY-ORG-330',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 80,
                'reorderQuantity' => 24,
                'description' => 'Royal Tru-Orange 330ml Can',
            ],
            [
                'name' => 'C2 Green Tea Apple',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 15,
                'productSalePrice' => 25,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'C2-APP-500',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 80,
                'reorderQuantity' => 20,
                'description' => 'C2 Green Tea Apple Flavor 500ml',
            ],
            [
                'name' => 'Nestea Iced Tea Lemon 330ml',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 18,
                'productSalePrice' => 28,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NES-LEM-330',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 60,
                'reorderQuantity' => 20,
                'description' => 'Nestea Iced Tea Lemon 330ml Can',
            ],

            // Snacks
            [
                'name' => 'Piattos Cheese',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 15,
                'productSalePrice' => 25,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'PIA-CHE-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 15,
                'description' => 'Piattos Cheese Flavored Chips 85g',
            ],
            [
                'name' => 'Nova Country Cheddar',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 12,
                'productSalePrice' => 20,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NOV-CHE-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 15,
                'description' => 'Nova Chips Country Cheddar 78g',
            ],
            [
                'name' => 'Chippy BBQ',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 10,
                'productSalePrice' => 18,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'CHI-BBQ-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 60,
                'reorderQuantity' => 15,
                'description' => 'Chippy BBQ Flavored Corn Chips 110g',
            ],
            [
                'name' => 'Oishi Prawn Crackers',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 12,
                'productSalePrice' => 22,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'OIS-PRW-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 15,
                'description' => 'Oishi Prawn Crackers Original 60g',
            ],
            [
                'name' => 'SkyFlakes Crackers',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 30,
                'productSalePrice' => 45,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'SKY-CRK-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 40,
                'reorderQuantity' => 10,
                'description' => 'SkyFlakes Saltine Crackers 250g',
            ],

            // Canned Goods
            [
                'name' => 'Century Tuna Flakes in Oil',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 35,
                'productSalePrice' => 48,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'CEN-TUN-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 60,
                'reorderQuantity' => 15,
                'description' => 'Century Tuna Flakes in Oil 155g',
            ],
            [
                'name' => 'Argentina Corned Beef',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 45,
                'productSalePrice' => 62,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'ARG-CRB-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 50,
                'reorderQuantity' => 12,
                'description' => 'Argentina Corned Beef 260g',
            ],
            [
                'name' => 'Spam Luncheon Meat',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 150,
                'productSalePrice' => 195,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'SPA-LUN-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 30,
                'reorderQuantity' => 10,
                'description' => 'Spam Classic Luncheon Meat 340g',
            ],

            // Rice & Staples
            [
                'name' => 'Sinandomeng Rice 5kg',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 280,
                'productSalePrice' => 350,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'SIN-RIC-5KG',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 25,
                'reorderQuantity' => 5,
                'description' => 'Premium Sinandomeng Rice 5kg',
            ],
            [
                'name' => 'Jasmine Rice 5kg',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 320,
                'productSalePrice' => 399,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'JAS-RIC-5KG',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 20,
                'reorderQuantity' => 5,
                'description' => 'Premium Jasmine Rice 5kg',
            ],

            // Bread & Bakery
            [
                'name' => 'Gardenia White Bread',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 65,
                'productSalePrice' => 82,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'GAR-WHT-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 20,
                'reorderQuantity' => 5,
                'description' => 'Gardenia Classic White Bread 600g',
            ],
            [
                'name' => 'Pandesal Pack of 10',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 35,
                'productSalePrice' => 50,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'PAN-SAL-010',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 30,
                'reorderQuantity' => 10,
                'description' => 'Fresh Pandesal Pack of 10 pieces',
            ],

            // Coffee & Beverages
            [
                'name' => 'Nescafe 3-in-1 Original',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 8,
                'productSalePrice' => 12,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'NES-3IN-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 30,
                'description' => 'Nescafe 3-in-1 Original Coffee Mix 28g',
            ],
            [
                'name' => 'Kopiko Brown Coffee',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 7,
                'productSalePrice' => 10,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'KOP-BRW-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 100,
                'reorderQuantity' => 30,
                'description' => 'Kopiko Brown Coffee Mix 27.5g',
            ],
            [
                'name' => 'Bear Brand Adult Plus',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 12,
                'productSalePrice' => 18,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'BEA-ADL-001',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 80,
                'reorderQuantity' => 20,
                'description' => 'Bear Brand Adult Plus Milk 33g',
            ],

            // Condiments
            [
                'name' => 'Datu Puti Soy Sauce 1L',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 55,
                'productSalePrice' => 75,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'DAT-SOY-1L',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 30,
                'reorderQuantity' => 10,
                'description' => 'Datu Puti Soy Sauce 1 Liter',
            ],
            [
                'name' => 'Datu Puti Vinegar 1L',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 40,
                'productSalePrice' => 55,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'DAT-VIN-1L',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 30,
                'reorderQuantity' => 10,
                'description' => 'Datu Puti White Vinegar 1 Liter',
            ],
            [
                'name' => 'UFC Banana Ketchup 320g',
                'productThumbnailImage' => 'default.jpg',
                'productPurchasePrice' => 35,
                'productSalePrice' => 48,
                'productSubCategoryId' => 1,
                'productBrandId' => 1,
                'sku' => 'UFC-KET-320',
                'uomId' => 1,
                'uomValue' => 1,
                'productVatId' => 1,
                'productQuantity' => 40,
                'reorderQuantity' => 10,
                'description' => 'UFC Banana Ketchup 320g',
            ],
        ];

        foreach ($products as $product) {
            // Override with dynamic IDs
            $product['productSubCategoryId'] = $subCategory->id;
            $product['productBrandId'] = $brand->id;
            $product['uomId'] = $uom->id;
            $product['productVatId'] = $vat->id;
            
            Product::create($product);
        }
    }
}
